[package]
name = "socute"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = { version = "0.12.1", features = ["serde"] }
chumsky = "0.10.1"
clap = { version = "4.5.40", features = ["derive"] }
color-eyre = "0.6.5"
env_logger = "0.11.8"
log = "0.4.27"
logos = "0.15.0"
