name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      RUSTC_WRAPPER: sccache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14-large, macos-14-xlarge]
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Compile
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Archive artefacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: socute-${{ matrix.os }}
          path: target/release/socute.exe
        if: matrix.os == 'windows-2022'

      - name: Archive artefacts (Unix)
        uses: actions/upload-artifact@v4
        with:
          name: socute-${{ matrix.os }}
          path: target/release/socute
        if: matrix.os != 'windows-2022'
